### ISSUE TITLE
quy trình nhập hàng hóa thông thường

### ISSUE THREAD

**Issue by nguyen-dc** [nguyen-dc/fish-webapps#5]
- Tạo phiếu nhập - danh sách chi tiết phiếu nhập 
- Tạo phiếu chi - danh sách chi tiết phiếu chi
    + Theo khai báo trong loại phiếu nhập có tạo phiếu chi hay không.
          + Nếu không tạo phiếu chi. Ẩn tab chi phí trong phiếu nhập.
    + Tách phiếu chi theo từng NCC. 
    + Nếu có chi phí: gom tất cả các loại chi phí vào 1 phiếu chi. Map với phiếu nhập dựa vào mã chứng từ.
- Thêm current in stock
    + Qui đổi về đơn vị tính chuẩn của sản phẩm để lưu tồn kho.

**Comment by CRXII** [comment]
Updated full: 
Mỗi phiếu chi chi cho 1 NCC. 
Trường hợp: không có hóa đơn đi kèm phiếu nhập => Phiếu nhập có thể nhập từ nhiều NCC.
Trường hợp: hóa đơn đi kèm phiếu nhập => Phiếu nhập chỉ được tạo cho 1 NCC. vì thông tin hóa đơn đi theo đúng từng NCC.

**1. Màn hình nhập hàng hóa thông thường: Tạo phiếu nhập - chi tiết phiếu nhập:**
Master:
- Loại phiếu nhập: chỉ load 2 mã: 1- Nhập đầu kỳ, 2-Nhập mua hàng hóa thông thường.
- Kho nhập: load kho thuộc loại 1 - Kho hàng thực tế.
- Sản phẩm: loại trừ ngành hàng 1- con giống, được chọn nhiều.
- NCC: load thông tin chi phánh NCC - chỉ chọn 1 trong 1 lần insert sản phẩm xuống lưới.
Detail - lưới:
- Field NCC: tự động fill NCC đã chọn trong pop-up.
- Field Số lượng: cho phép nhập.
- Field ĐVT: load theo ĐVT chuẩn của sản phẩm.
- Field VAT: load % VAT theo sản phẩm
Tab chi phí:
- Cho phép insert nhiều loại chi phí xuống lưới.
- Số tiền nhập vào là tiền đã bao gồm VAT.
- %VAT mặc định của chi phí: 10%.

**2. Tạo phiếu chi - chi tiết phiếu chi:**
- Tạo phiếu chi theo thiết lập trong loại phiếu nhập (có tạo/không tạo).
- Tạo từng phiếu chi riêng cho từng NCC.
- Chi tiết phiếu chi của NCC: loại phiếu chi theo khai báo của loại phiếu nhập. Sản phẩm theo NCC khi trên lưới.
- Phần chi phí chung của phiếu nhập: gom lại tạo thành 1 phiếu chi riêng. Map với nhau qua mã phiếu nhập.

**3. Cập nhật tồn kho:**
- Qui đổi về ĐVT chuẩn để nhập kho.
- Dựa vào trạng thái thực nhập: để cập nhật số lượng tồn và thực tồn theo sản phẩm trong kho.
